import { ethers } from 'ethers';
import { PramanConfig, AuthResult, PopupOptions, PopupAuthResult } from './types';
import { quantizeFaceVector, hashFaceVector } from './biometrics';
import { generateZKFaceProof } from './zkLayer';
import { encryptPII, uploadToIPFS, getManualAuthSig, decryptPII, getPermissionAuthSig, fetchFromIPFS } from './storageLayer';
import faceRegistryConfig from './contracts/FaceRegistry.json';

// Helper to get environment variable across builders
const getSDKDefaultRelayerUrl = (): string => {
  if (typeof process !== 'undefined' && process.env) {
    if (process.env.NEXT_PUBLIC_API_URL) return process.env.NEXT_PUBLIC_API_URL;
    if (process.env.VITE_BACKEND_URL) return process.env.VITE_BACKEND_URL;
  }
  try {
    // @ts-ignore
    if (typeof import.meta !== 'undefined' && import.meta.env) {
      // @ts-ignore
      if (import.meta.env.NEXT_PUBLIC_API_URL) return import.meta.env.NEXT_PUBLIC_API_URL;
      // @ts-ignore
      if (import.meta.env.VITE_BACKEND_URL) return import.meta.env.VITE_BACKEND_URL;
    }
  } catch (e) {}
  return 'https://api.praman.network';
};

export const DEFAULT_RELAYER_URL = getSDKDefaultRelayerUrl();

// Keep global client instance
let globalClientInstance: PramanClient | null = null;

export class PramanClient {
  private apiKey: string;
  private network: string;
  private webhookUrl?: string;
  private backendUrl: string;
  private adminAddress: string;
  private livenessLevel: 'strict' | 'standard' | 'off';
  private idpUrl: string;

  constructor(config: PramanConfig) {
    this.apiKey = config.apiKey;
    this.network = config.network;
    this.webhookUrl = config.webhookUrl;
    this.backendUrl = config.backendUrl || DEFAULT_RELAYER_URL;
    this.adminAddress = config.adminAddress || '0x499B85172C9a228eaE3D7723223DFF062bFdFd4D';
    this.idpUrl = config.idpUrl || 'https://auth.praman.network/authorize';

    // Normalize liveness level config
    if (config.livenessLevel) {
      this.livenessLevel = config.livenessLevel;
    } else if (config.liveness === true) {
      this.livenessLevel = 'standard';
    } else if (config.liveness === false || config.liveness === 'off') {
      this.livenessLevel = 'off';
    } else if (config.liveness === 'strict' || config.liveness === 'standard') {
      this.livenessLevel = config.liveness;
    } else {
      this.livenessLevel = 'standard';
    }

    this.validateApiKey();
  }

  /**
   * Retrieves or generates a local ephemeral wallet for the current user session.
   * This allows gasless transactions and login without MetaMask popups.
   */
  private getLocalEphemeralWallet(): ethers.Wallet {
    if (typeof window === 'undefined') {
      throw new Error('[PramanSDK] Ephemeral wallets can only be used in browser environments.');
    }
    let privateKey = localStorage.getItem('praman_local_ephemeral_key');
    if (!privateKey) {
      const newWallet = ethers.Wallet.createRandom();
      localStorage.setItem('praman_local_ephemeral_key', newWallet.privateKey);
      privateKey = newWallet.privateKey;
    }
    return new ethers.Wallet(privateKey);
  }

  public getLivenessLevel(): 'strict' | 'standard' | 'off' {
    return this.livenessLevel;
  }

  /**
   * Validates the provided API key (placeholder pattern match for licensing/billing checks).
   */
  private validateApiKey() {
    if (!this.apiKey || !this.apiKey.startsWith('pm_')) {
      console.warn(
        `[PramanSDK] Warning: API key "${this.apiKey}" does not follow the standard "pm_..." format. ` +
        'Please ensure you are using a valid SDK client key.'
      );
    }
  }

  /**
   * Triggers background analytics/usage tracking webhook event.
   */
  private async trackUsage(event: 'register' | 'login', address: string, success: boolean) {
    console.log(`[PramanSDK] Tracking event: ${event} for ${address} (success: ${success})`);
    
    if (this.webhookUrl) {
      try {
        await fetch(this.webhookUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': this.apiKey,
          },
          body: JSON.stringify({
            event,
            address,
            success,
            network: this.network,
            timestamp: new Date().toISOString(),
          }),
        });
      } catch (err) {
        console.warn('[PramanSDK] Non-blocking tracking webhook notification failed:', err);
      }
    }
  }

  /**
   * Constructs a decentralized wallet-signed JWT.
   * Format: base64(header).base64(payload).signature
   * The signature is generated by the user signing the first two segments.
   */
  private async generateWalletSignedToken(
    signer: any,
    userAddress: string,
    faceHash: string,
    ipfsCid: string,
    name?: string,
    expiryDuration?: number,
    isMock?: boolean
  ): Promise<string> {
    const header = {
      alg: 'ETH_SIGN',
      typ: 'JWT',
    };
    
    const iat = Math.floor(Date.now() / 1000);
    const exp = iat + (expiryDuration || 3600); // 1 hour expiration
    const payload: any = {
      sub: userAddress.toLowerCase(),
      faceHash,
      ipfsCid,
      iat,
      exp,
      iss: 'pramanauth',
      is_mock: isMock ?? false,
    };

    if (name) {
      payload.name = name;
    }

    const headerB64 = btoa(JSON.stringify(header))
      .replace(/=/g, '')
      .replace(/\+/g, '-')
      .replace(/\//g, '_');
      
    const payloadB64 = btoa(JSON.stringify(payload))
      .replace(/=/g, '')
      .replace(/\+/g, '-')
      .replace(/\//g, '_');

    const messageToSign = `${headerB64}.${payloadB64}`;
    
    // Request a signature from the user's wallet
    const signature = await signer.signMessage(messageToSign);

    return `${messageToSign}.${signature}`;
  }

  /**
   * Core Register logic wrapping extraction outputs and relayer submission.
   */
  public async register(
    webcamScreenshot: string,
    pii: { name: string; email: string; mobile: string },
    signer: any,
    faceapiInstance: any,
    onProgress?: (progress: { step: string; message: string }) => void
  ): Promise<AuthResult> {
    const log = (step: string, message: string) => {
      console.log(`[PramanSDK Register] ${message}`);
      if (onProgress) onProgress({ step, message });
    };

    const activeSigner = signer || this.getLocalEphemeralWallet();
    let userAddress = '';
    try {
      userAddress = await activeSigner.getAddress();
      log('connecting-wallet', `Registering address: ${userAddress}`);

      // 1. Process Frame (Face detection)
      log('scanning-face', 'Extracting facial profile descriptors...');
      const img = new Image();
      img.src = webcamScreenshot;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = () => reject(new Error('Failed to parse webcam image screenshot'));
      });

      const detection = await faceapiInstance
        .detectSingleFace(img, new faceapiInstance.SsdMobilenetv1Options({ minConfidence: 0.5 }))
        .withFaceLandmarks()
        .withFaceDescriptor();

      if (!detection) {
        throw new Error('No face detected. Adjust lighting and face position.');
      }

      const faceVector = Array.from(detection.descriptor) as number[];
      const quantizedNewVector = quantizeFaceVector(faceVector);
      const faceDescriptorHash = hashFaceVector(quantizedNewVector);
      log('generating-vector', `Face vector quantized. Keccak Hash: ${faceDescriptorHash}`);

      // 2. Encryption via Lit Protocol (strictly enforced)
      log('encrypting-pii', 'Securing PII payloads via decentralized Lit protocol...');
      const authSig = await getManualAuthSig(activeSigner);
      const encryptionResult = await encryptPII(pii, userAddress, this.adminAddress, authSig);
      
      // 3. Post payload to Backend Relayer for IPFS pinning and on-chain deployment
      log('registering-on-chain', 'Sending registration details to Backend Relayer...');
      const response = await fetch(`${this.backendUrl}/api/auth/register`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          apiKey: this.apiKey,
          userAddress,
          faceDescriptorHash,
          quantizedVector: quantizedNewVector,
          ciphertext: encryptionResult.ciphertext,
          dataToEncryptHash: encryptionResult.dataToEncryptHash,
          authSig,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Relayer Registration failed: ${errorText}`);
      }

      const relayerResult = await response.json();
      if (!relayerResult.success) {
        throw new Error(`Relayer Registration failed: ${relayerResult.error}`);
      }

      // Generate JWT Token locally using active ephemeral/MetaMask wallet
      const jwt = await this.generateWalletSignedToken(
        activeSigner,
        userAddress,
        faceDescriptorHash,
        relayerResult.ipfsCid,
        pii.name
      );

      await this.trackUsage('register', userAddress, true);
      return {
        success: true,
        jwt,
        faceDescriptorHash,
        ipfsCid: relayerResult.ipfsCid,
        pii,
      };
    } catch (err: any) {
      const errMsg = err.message || 'SDK Registration failed';
      await this.trackUsage('register', userAddress || 'unknown', false);
      return {
        success: false,
        jwt: '',
        error: errMsg,
      };
    }
  }

  /**
   * Core Login logic wrapping face-matching, ZK Proof validation, and Relayer verification.
   */
  public async login(
    webcamScreenshot: string,
    signer: any,
    faceapiInstance: any,
    onProgress?: (progress: { step: string; message: string }) => void
  ): Promise<AuthResult> {
    const log = (step: string, message: string) => {
      console.log(`[PramanSDK Login] ${message}`);
      if (onProgress) onProgress({ step, message });
    };

    const activeSigner = signer || this.getLocalEphemeralWallet();
    let userAddress = '';
    try {
      userAddress = await activeSigner.getAddress();
      log('connecting-wallet', `Logging in address: ${userAddress}`);

      // 1. Process Frame (Face detection)
      log('scanning-face', 'Extracting facial profile descriptors...');
      const img = new Image();
      img.src = webcamScreenshot;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = () => reject(new Error('Failed to parse webcam image screenshot'));
      });

      const detection = await faceapiInstance
        .detectSingleFace(img, new faceapiInstance.SsdMobilenetv1Options({ minConfidence: 0.5 }))
        .withFaceLandmarks()
        .withFaceDescriptor();

      if (!detection) {
        throw new Error('No face detected. Adjust lighting and face position.');
      }

      const faceVector = Array.from(detection.descriptor) as number[];
      const quantizedNewVector = quantizeFaceVector(faceVector);
      const faceDescriptorHash = hashFaceVector(quantizedNewVector);
      log('generating-vector', `Face vector quantized. Keccak Hash: ${faceDescriptorHash}`);

      // 2. Fetch Registration details from contract (Free read-only RPC call, no MetaMask popup!)
      log('checking-duplicate', 'Querying registry contract for existing identity record...');
      const readProvider = new ethers.JsonRpcProvider('https://rpc-amoy.polygon.technology');
      const contract = new ethers.Contract(faceRegistryConfig.address, faceRegistryConfig.abi, readProvider);
      
      const storedFaceHash = await contract.getUserFaceHash(userAddress);
      const zeroHash = '0x0000000000000000000000000000000000000000000000000000000000000000';
      const isRegistered = (storedFaceHash !== zeroHash && storedFaceHash !== '0x');

      if (!isRegistered) {
        throw new Error('User not found. Please Register first.');
      }

      const registeredCid = await contract.getUserCid(userAddress);
      const registeredHash = storedFaceHash;

      // 3. Load Saved Vector from IPFS
      log('generating-vector', 'Fetching reference biometric template from IPFS...');
      const payload = await fetchFromIPFS(registeredCid);
      const savedVector = payload.quantizedVector;

      if (!savedVector || savedVector.length !== 128) {
        throw new Error('Registered biometric template not found in IPFS payload.');
      }

      // 4. Generate ZK Face proof locally
      log('generating-zk-proof', 'Running snarkjs.groth16 zero-knowledge proving verification...');
      const zkResult = await generateZKFaceProof(quantizedNewVector, savedVector, registeredHash);

      // 5. Send ZK Proof to Backend Relayer for verification
      log('generating-zk-proof', 'Verifying ZK proof off-chain on the Backend Relayer...');
      const response = await fetch(`${this.backendUrl}/api/auth/login`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          apiKey: this.apiKey,
          userAddress,
          zkProof: zkResult.proof,
          publicSignals: zkResult.publicSignals,
          is_mock: zkResult.is_mock,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Relayer Verification failed: ${errorText}`);
      }

      const relayerResult = await response.json();
      if (!relayerResult.success || !relayerResult.verified) {
        throw new Error(`Relayer Verification failed: ${relayerResult.error || 'Proof rejected'}`);
      }

      // 6. Decrypt profile name (optional) from encrypted storage
      let name: string | undefined = undefined;
      let decryptedPII: any = undefined;
      try {
        const authSig = await getManualAuthSig(activeSigner);
        const decrypted = await decryptPII(
          payload.ciphertext,
          payload.dataToEncryptHash,
          userAddress,
          this.adminAddress,
          authSig
        );
        name = decrypted.name;
        decryptedPII = decrypted;
      } catch (e) {
        console.warn('[PramanSDK] Failed to retrieve name during login, proceeding without it:', e);
      }

      // Generate JWT Token locally
      const jwt = await this.generateWalletSignedToken(
        activeSigner,
        userAddress,
        registeredHash,
        registeredCid,
        name,
        undefined,
        zkResult.is_mock
      );

      await this.trackUsage('login', userAddress, true);
      return {
        success: true,
        jwt,
        proof: zkResult.proof,
        faceDescriptorHash: registeredHash,
        ipfsCid: registeredCid,
        is_mock: zkResult.is_mock,
        pii: decryptedPII,
      };
    } catch (err: any) {
      const errMsg = err.message || 'SDK Login failed';
      await this.trackUsage('login', userAddress || 'unknown', false);
      return {
        success: false,
        jwt: '',
        error: errMsg,
      };
    }
  }

  /**
   * Verifies the decentralized wallet-signed JWT token.
   * Can be used in both frontend and backend.
   */
  public verifyToken(token: string): { valid: boolean; payload?: any; error?: string } {
    try {
      const parts = token.split('.');
      if (parts.length !== 3) {
        throw new Error('Invalid token structure');
      }

      const [headerB64, payloadB64, signature] = parts;
      
      // Decode payload
      const payloadString = atob(payloadB64.replace(/-/g, '+').replace(/_/g, '/'));
      const payload = JSON.parse(payloadString);

      // Validate expiration
      if (payload.exp && Date.now() / 1000 > payload.exp) {
        throw new Error('Token has expired');
      }

      // Verify the wallet signature
      const messageToVerify = `${headerB64}.${payloadB64}`;
      const recoveredAddress = ethers.verifyMessage(messageToVerify, signature);

      if (recoveredAddress.toLowerCase() !== payload.sub.toLowerCase()) {
        throw new Error('Signature address mismatch');
      }

      return {
        valid: true,
        payload,
      };
    } catch (err: any) {
      return {
        valid: false,
        error: err.message || 'Token verification failed',
      };
    }
  }

  /**
   * Decrypts and retrieves the sensitive PII (email and mobile phone)
   * after requesting a new EIP-4361 SIWE message with 'permission' scope.
   */
  public async decryptSensitivePII(
    ipfsCid: string,
    signer: any
  ): Promise<{ email: string; mobile: string }> {
    const userAddress = await signer.getAddress();
    
    // Fetch directly from IPFS (strictly required, no local storage caching)
    const payload = await fetchFromIPFS(ipfsCid);

    // Request the user to sign a SIWE message with 'permission' scope
    const authSig = await getPermissionAuthSig(signer);

    // Decrypt the full PII
    const decrypted = await decryptPII(
      payload.ciphertext,
      payload.dataToEncryptHash,
      userAddress,
      this.adminAddress,
      authSig
    );

    return {
      email: decrypted.email,
      mobile: decrypted.mobile,
    };
  }

  /**
   * Internal helper to open the popup and handle window messaging.
   */
  private launchPopupFlow(mode: 'login' | 'register', options?: PopupOptions): Promise<PopupAuthResult> {
    if (typeof window === 'undefined') {
      return Promise.reject(new Error('[PramanSDK] Popup authentication is only supported in browser environments.'));
    }

    const width = options?.width || 500;
    const height = options?.height || 700;
    
    // Center popup window
    const left = window.screen.width / 2 - width / 2;
    const top = window.screen.height / 2 - height / 2;

    const baseIdpUrl = options?.idpUrl || this.idpUrl;
    
    // Construct query parameters
    const queryParams = new URLSearchParams({
      mode,
      apiKey: this.apiKey,
      network: this.network,
      backendUrl: this.backendUrl,
      livenessLevel: this.livenessLevel,
      adminAddress: this.adminAddress,
    });
    
    if (options?.scopes && options.scopes.length > 0) {
      queryParams.append('scopes', options.scopes.join(','));
    }

    const popupUrl = `${baseIdpUrl}?${queryParams.toString()}`;
    const windowFeatures = `width=${width},height=${height},top=${top},left=${left},status=no,resizable=yes,scrollbars=yes`;

    return new Promise<PopupAuthResult>((resolve, reject) => {
      const popup = window.open(popupUrl, 'PramanAuthPopup', windowFeatures);

      if (!popup) {
        reject(new Error('Popup blocked. Please allow popups for this site.'));
        return;
      }

      const messageListener = (event: MessageEvent) => {
        const { data } = event;
        
        // Simple safety check: check structure of data
        if (data && typeof data === 'object') {
          if (data.type === 'PRAMAN_AUTH_SUCCESS') {
            window.removeEventListener('message', messageListener);
            clearInterval(closeCheckInterval);
            resolve(data.payload as PopupAuthResult);
          } else if (data.type === 'PRAMAN_AUTH_ERROR') {
            window.removeEventListener('message', messageListener);
            clearInterval(closeCheckInterval);
            reject(new Error(data.error || 'Authentication failed.'));
          }
        }
      };

      window.addEventListener('message', messageListener);

      const closeCheckInterval = setInterval(() => {
        if (popup.closed) {
          clearInterval(closeCheckInterval);
          window.removeEventListener('message', messageListener);
          reject(new Error('User closed the verification window.'));
        }
      }, 1000);
    });
  }

  /**
   * Initiates a login flow inside a centered popup window.
   */
  public async loginWithPopup(options?: PopupOptions): Promise<PopupAuthResult> {
    return this.launchPopupFlow('login', options);
  }

  /**
   * Initiates a registration flow inside a centered popup window.
   */
  public async registerWithPopup(options?: PopupOptions): Promise<PopupAuthResult> {
    return this.launchPopupFlow('register', options);
  }
}

/**
 * Initializes standard Praman SDK client.
 */
export function initPraman(config: PramanConfig): PramanClient {
  if (!globalClientInstance) {
    globalClientInstance = new PramanClient(config);
  }
  return globalClientInstance;
}
